/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-use'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-use'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-use'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
